apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
  labels:
    app.kubernetes.io/name: load-tester
    app.kubernetes.io/component: load-tester
    app.kubernetes.io/part-of: istio-mtls-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-tester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-tester
        app.kubernetes.io/component: load-tester
        app.kubernetes.io/part-of: istio-mtls-lab
    spec:
      containers:
        - name: load-tester
          image: fortio/fortio:1.69.0
          command:
            - /usr/bin/fortio
            - server
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8079
              name: grpc
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /fortio/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /fortio/
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
