apiVersion: v1
kind: Namespace
metadata:
  name: lab-mesh
  labels:
    app.kubernetes.io/part-of: istio-mtls-lab
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-external
  labels:
    app.kubernetes.io/part-of: istio-mtls-lab
